# Codebook for output data set
The following file contains descriptions of the columns present in the output data file generated by running run_analysis.R on the source files contained in the [http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones](UCI HAR Dataset). (See README.MD for details.)

## subject
Contains the unique identifier of a research subject as an integer

## activityName
Contains one of the following values as a character:

- LAYING 
- SITTING
- STANDING
- WALKING
- WALKING_DOWNSTAIRS
- WALKING_UPSTAIRS

These values refer to the activity related to the measure for which the observation accounts.

## measureName 
This refers the the name of the measure for which the observation accounts. See original research publications for details. The possible values are as follows:

- tBodyAcc.mean.X
- tBodyAcc.mean.Y
- tBodyAcc.mean.Z
- tGravityAcc.mean.X
- tGravityAcc.mean.Y
- tGravityAcc.mean.Z
- tBodyAccJerk.mean.X
- tBodyAccJerk.mean.Y
- tBodyAccJerk.mean.Z
- tBodyGyro.mean.X
- tBodyGyro.mean.Y
- tBodyGyro.mean.Z
- tBodyGyroJerk.mean.X
- tBodyGyroJerk.mean.Y
- tBodyGyroJerk.mean.Z
- tBodyAccMag.mean
- tGravityAccMag.mean
- tBodyAccJerkMag.mean
- tBodyGyroMag.mean
- tBodyGyroJerkMag.mean
- fBodyAcc.mean.X
- fBodyAcc.mean.Y
- fBodyAcc.mean.Z
- fBodyAcc.meanFreq.X
- fBodyAcc.meanFreq.Y
- fBodyAcc.meanFreq.Z
- fBodyAccJerk.mean.X
- fBodyAccJerk.mean.Y
- fBodyAccJerk.mean.Z
- fBodyAccJerk.meanFreq.X
- fBodyAccJerk.meanFreq.Y
- fBodyAccJerk.meanFreq.Z
- fBodyGyro.mean.X
- fBodyGyro.mean.Y
- fBodyGyro.mean.Z
- fBodyGyro.meanFreq.X
- fBodyGyro.meanFreq.Y
- fBodyGyro.meanFreq.Z
- fBodyAccMag.mean
- fBodyAccMag.meanFreq
- fBodyBodyAccJerkMag.mean
- fBodyBodyAccJerkMag.meanFreq
- fBodyBodyGyroMag.mean
- fBodyBodyGyroMag.meanFreq
- fBodyBodyGyroJerkMag.mean
- fBodyBodyGyroJerkMag.meanFreq
- angle.tBodyAccMean.gravity.
- angle.tBodyAccJerkMeangravityMean.
- angle.tBodyGyroMean.gravityMean.
- angle.tBodyGyroJerkMean.gravityMean.
- angle.X.gravityMean.
- angle.Y.gravityMean.
- angle.Z.gravityMean.
- tBodyAcc.std.X
- tBodyAcc.std.Y
- tBodyAcc.std.Z
- tGravityAcc.std.X
- tGravityAcc.std.Y
- tGravityAcc.std.Z
- tBodyAccJerk.std.X
- tBodyAccJerk.std.Y
- tBodyAccJerk.std.Z
- tBodyGyro.std.X
- tBodyGyro.std.Y
- tBodyGyro.std.Z
- tBodyGyroJerk.std.X
- tBodyGyroJerk.std.Y
- tBodyGyroJerk.std.Z
- tBodyAccMag.std
- tGravityAccMag.std
- tBodyAccJerkMag.std
- tBodyGyroMag.std
- tBodyGyroJerkMag.std
- fBodyAcc.std.X
- fBodyAcc.std.Y
- fBodyAcc.std.Z
- fBodyAccJerk.std.X
- fBodyAccJerk.std.Y
- fBodyAccJerk.std.Z
- fBodyGyro.std.X
- fBodyGyro.std.Y
- fBodyGyro.std.Z
- fBodyAccMag.std
- fBodyBodyAccJerkMag.std
- fBodyBodyGyroMag.std
- fBodyBodyGyroJerkMag.std

## measureValue
Numeric value for the given measure
